data_source:
  pdf_path: Source\Data\raw_data\EPF_compliance.pdf
  docx_path: Source\Data\raw_data\EPF_compliance.docx

model:
  embedding: sentence-transformers/all-MiniLM-L6-v2
  generation: gpt-3.5-turbo