#data ingestion config
data_source:
  pdf_path: Source\Data\raw_data\EPF_compliance.pdf
  docx_path: Source\Data\raw_data\EPF_compliance.docx

#data chunking config
data_chunking:
  recursive_text_splitter:
    chunk_size: 50
    chunk_overlap: 10

#